version: "3.9"
services:
  downloader:
    build:
      context: .
    image: tdps-downloader:latest
    container_name: tdps-downloader
    # command: [ "python", "./tdps-downloader.py", "2022-05-27" ]
    environment:
      - TZ=America/Toronto
    volumes:
      - .env:/app/.env
      - tdps_downloads:/app/downloads

volumes:
  tdps_downloads:
    name: tdps_downloads
    driver: local