version: "3.9"
services:
  downloader:
    build:
      context: .
    image: tdps-downloader:latest
    command: [ "python", "./tdps-downloader.py" ]
    environment:
      - TZ=America/Toronto
    volumes:
      - ./downloads:/app/downloads
      - .env:/app/.env
